org: markawaii
service: aws-express

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:601134614454:table/CompensacionesTableNew

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    CompensacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CompensacionesTableNew
        BillingMode: PAY_PER_REQUEST  ## cobra por la cantidad de peticiones realizadas
        AttributeDefinitions:
          - AttributeName: id_sap
            AttributeType: S
        KeySchema:
          - AttributeName: id_sap
            KeyType: HASH