org: markawaii
service: aws-express

custom:
  tableCompensacionesAgnos: 'compensaciones-agno-table' ## esto se asignara en provider y en el nombre de la tabla

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:601134614454:table/${self:custom.tableCompensacionesAgnos} ## permite almacenar y modificar información en la tabla
  environment:
    COMPENSACIONES_AGNO_TABLE: ${self:custom.tableCompensacionesAgnos}

plugins:
  - serverless-offline # para instalar este plugins son necesarios los siguiente 2 o si no se hará el deploy
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    CompensacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableCompensacionesAgnos}  # Nombre actualizado de la tabla
        BillingMode: PAY_PER_REQUEST  # Cobra por la cantidad de peticiones realizadas
        AttributeDefinitions:
          - AttributeName: id_sap
            AttributeType: S
        KeySchema:
          - AttributeName: id_sap
            KeyType: HASH
