org: markawaii
service: aws-express

custom:
  tableCompensacionesAgnos: 'compensaciones-agno-table' ## esto se asignara en provider y en el nombre de la tabla

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:601134614454:table/${self:custom.tableCompensacionesAgnos} ## permite almacenar y modificar información en la tabla
  environment:
    COMPENSACIONES_AGNO_TABLE: ${self:custom.tableCompensacionesAgnos}

plugins:
  - serverless-offline
  # - serverless-dynamodb-local
  # - serverless-dynamodb
  - serverless-plugin-common-excludes # Se instala el plugin serverless-plugin-common-excludes que reduce el tamaño de los paquetes, lo cual tambien soluciona el problema de los deploy
  - serverless-plugin-include-dependencies # El plugin 'serverless-offline' depende de este
  

functions:
  api:
    handler: handler.handler
    # timeout: 30  # Increasing timeout to 30 secondsn # verificar porque falla al hacer el deploy
    events:
      - httpApi: "*"


resources:
  Resources:
    CompensacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableCompensacionesAgnos}  # Nombre actualizado de la tabla
        BillingMode: PAY_PER_REQUEST  # Cobra por la cantidad de peticiones realizadas
        AttributeDefinitions:
          - AttributeName: id_sap
            AttributeType: S
        KeySchema:
          - AttributeName: id_sap
            KeyType: HASH
