org: markawaii
service: aws-express

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:601134614454:table/CompensacionesTableNew ## permite almacenar informaicion en la tabla

plugins:
  - serverless-offline # para instalar este plugins son nesesarios los siguiente 2 o si no se se hara el deploy
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    CompensacionesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CompensacionesTableNew ## nombre de la tabla que estamos creando
        BillingMode: PAY_PER_REQUEST ## cobra por la cantidad de peticiones realizadas
        AttributeDefinitions:
          - AttributeName: id_sap
            AttributeType: S
        KeySchema:
          - AttributeName: id_sap
            KeyType: HASH
